import { z } from 'zod'
import { CONTENT_FORMATS, KNOWLEDGE_TYPES, REVIEW_REASONS, THESIS_STATUSES } from './types'

const optionalTextArray = z.array(z.string().trim().min(1)).default([])
const optionalUuid = z.string().uuid().optional().nullable()
export const createThesisSchema = z.object({ title: z.string().trim().min(3).max(500), slug: z.string().trim().min(3).max(255).regex(/^[a-z0-9-]+$/).optional(), summary: z.string().max(5000).optional(), coreStatement: z.string().trim().min(10), fullText: z.string().max(100000).optional(), status: z.enum(THESIS_STATUSES).default('draft'), priority: z.coerce.number().int().min(0).max(100).default(0), weight: z.coerce.number().positive().max(100).default(1).transform(String), tone: z.string().max(100).optional(), depthLevel: z.string().max(100).optional(), audienceStage: z.string().max(100).optional(), allowedCta: optionalTextArray, recommendedFormats: optionalTextArray, vocabulary: optionalTextArray, forbiddenWords: optionalTextArray, beliefsToReinforce: optionalTextArray, beliefsToCombat: optionalTextArray, commonErrors: optionalTextArray, tags: optionalTextArray })
export const updateThesisSchema = createThesisSchema.partial().extend({ changeReason: z.string().max(1000).optional() })
export const createArgumentSchema = z.object({ type: z.enum(['primary', 'secondary']), title: z.string().min(2).max(500), content: z.string().min(2), position: z.coerce.number().int().min(0).default(0) })
export const createObjectionSchema = z.object({ objection: z.string().min(2), response: z.string().min(2), frequency: z.enum(['high', 'medium', 'low']).default('medium'), position: z.coerce.number().int().min(0).default(0) })
export const createExampleSchema = z.object({ title: z.string().min(2).max(500), content: z.string().min(2), type: z.enum(['example', 'analogy', 'case_study']), position: z.coerce.number().int().min(0).default(0) })
export const createEvidenceSchema = z.object({ title: z.string().min(2).max(500), content: z.string().min(2), sourceUrl: z.url().optional().or(z.literal('')), sourceName: z.string().max(500).optional(), position: z.coerce.number().int().min(0).default(0) })
export const createDocumentSchema = z.object({ title: z.string().min(2).max(500), type: z.enum(KNOWLEDGE_TYPES).default('text'), contentText: z.string().min(1).max(2_000_000), thesisId: optionalUuid, tags: optionalTextArray, language: z.string().max(20).default('pt-BR') })
export const createCampaignSchema = z.object({ title: z.string().min(2).max(500), description: z.string().max(5000).optional(), startDate: z.iso.date(), endDate: z.iso.date(), preset: z.string().max(100).optional(), config: z.record(z.string(), z.unknown()).default({}) }).refine((value) => value.endDate >= value.startDate, { message: 'A data final deve ser posterior à inicial', path: ['endDate'] })
export const createPlanSchema = z.object({ campaignId: z.string().uuid(), title: z.string().min(2).max(500), periodStart: z.iso.date(), periodEnd: z.iso.date(), quantities: z.object({ post: z.coerce.number().int().min(0).optional(), carousel: z.coerce.number().int().min(0).optional(), story: z.coerce.number().int().min(0).optional(), slide: z.coerce.number().int().min(0).optional(), document: z.coerce.number().int().min(0).optional() }).default({}), thesisIds: z.array(z.string().uuid()).min(1), config: z.record(z.string(), z.unknown()).default({}) })
export const createPlanItemSchema = z.object({ format: z.enum(CONTENT_FORMATS), thesisId: z.string().uuid(), intentId: optionalUuid, angleId: optionalUuid, scheduledDate: z.iso.date().optional().nullable(), hookStrategy: z.string().max(255).optional(), depthLevel: z.string().max(100).optional(), audienceStage: z.string().max(100).optional(), cta: z.string().max(2000).optional(), visualDirection: z.string().max(5000).optional(), coreArgumentId: optionalUuid, templateSuggestion: z.string().max(100).optional() })
export const createBriefSchema = z.object({ planItemId: z.string().uuid(), thesisId: z.string().uuid(), format: z.enum(CONTENT_FORMATS), intent: z.string().optional(), angle: z.string().optional(), coreArgument: z.string().min(1), supportingPoints: optionalTextArray, evidenceIds: z.array(z.string().uuid()).default([]), cta: z.string().optional(), visualDirection: z.string().optional(), avoid: optionalTextArray, thesisVersion: z.coerce.number().int().positive() })
export const createContentItemSchema = z.object({ thesisId: z.string().uuid(), format: z.enum(CONTENT_FORMATS), copyData: z.record(z.string(), z.unknown()), planItemId: optionalUuid, briefId: optionalUuid, templateId: z.string().max(100).optional() })
export const createReviewSchema = z.object({ reviewer: z.string().min(1).max(255).default('editor'), action: z.enum(['approve', 'reject', 'request_revision']), reasonCode: z.enum(REVIEW_REASONS).optional(), comment: z.string().max(5000).optional() })
export const structureThesisSchema = z.object({ text: z.string().min(30).max(100000) })
