import type { ContentFormat } from '@/domain/editorial/types'

export interface PlannerThesis { id: string; priority: number; weight: string | number; depthLevel: string | null; audienceStage: string | null; allowedCta: string[] | null; recommendedFormats: string[] | null }
export interface PlannerTaxon { id: string; name: string }
export interface PlannedItem { position: number; scheduledDate: string; format: ContentFormat; thesisId: string; intentId?: string; angleId?: string; hookStrategy: string; depthLevel: string | null; audienceStage: string | null; cta: string | null; templateSuggestion?: string }
const hooks = ['O erro que quase todos cometem', 'O que ninguém explica sobre isso', 'Antes de fazer isso, entenda', 'A diferença que muda o resultado', 'Um caminho prático para aplicar hoje']
const asNumber = (value: string | number) => typeof value === 'number' ? value : Number(value)
export function generatePlan(input: { theses: PlannerThesis[]; intents: PlannerTaxon[]; angles: PlannerTaxon[]; quantities: Partial<Record<ContentFormat, number>>; start: string; end: string; minimumGap?: number }): PlannedItem[] {
  const formats = (Object.entries(input.quantities) as Array<[ContentFormat, number]>).flatMap(([format, count]) => Array.from({ length: count }, () => format)); const totalWeight = input.theses.reduce((sum, thesis) => sum + Math.max(.1, asNumber(thesis.weight)) * Math.max(1, thesis.priority + 1), 0); const quotas = input.theses.map((thesis) => ({ thesis, target: formats.length * (Math.max(.1, asNumber(thesis.weight)) * Math.max(1, thesis.priority + 1)) / totalWeight, assigned: 0, lastPosition: -Infinity })); const start = new Date(`${input.start}T12:00:00`); const minimumGap = input.minimumGap ?? 2
  return formats.map((format, position) => { const eligible = quotas.filter((item) => position - item.lastPosition >= minimumGap); const selected = (eligible.length ? eligible : quotas).sort((a, b) => (a.assigned - a.target) - (b.assigned - b.target) || a.lastPosition - b.lastPosition)[0]!; selected.assigned += 1; selected.lastPosition = position; const thesis = selected.thesis; const date = new Date(start); date.setDate(start.getDate() + position); const intent = input.intents[position % Math.max(input.intents.length, 1)]; const angle = input.angles[(position + Math.floor(position / Math.max(input.theses.length, 1))) % Math.max(input.angles.length, 1)]; return { position, scheduledDate: date.toISOString().slice(0, 10), format, thesisId: thesis.id, intentId: intent?.id, angleId: angle?.id, hookStrategy: hooks[position % hooks.length]!, depthLevel: thesis.depthLevel, audienceStage: thesis.audienceStage, cta: thesis.allowedCta?.[position % Math.max(thesis.allowedCta.length, 1)] ?? null } })
}
