import { and, desc, eq } from 'drizzle-orm'
import { Hono } from 'hono'
import { knowledgeChunks, knowledgeDocuments } from '@/db/editorial-schema'
import { createDocumentSchema } from '@/domain/editorial/schemas'
import { chunkDocument, contentHash, normalizeText, wordCount } from '@/server/editorial/ingest'
import { searchKnowledge } from '@/server/editorial/search'
import { db } from '../db'
import { body, notFound } from './helpers'

export const knowledgeRoutes = new Hono()
async function indexDocument(document: { id: string; contentText: string; thesisId: string | null; tags: string[] | null; language: string }) { const chunks = chunkDocument(document.contentText); await db.delete(knowledgeChunks).where(eq(knowledgeChunks.documentId, document.id)); if (chunks.length) await db.insert(knowledgeChunks).values(chunks.map((chunk) => ({ ...chunk, documentId: document.id, normalizedContent: normalizeText(chunk.content).toLowerCase(), thesisId: document.thesisId, tags: document.tags ?? [], language: document.language }))); await db.update(knowledgeDocuments).set({ status: 'indexed', updatedAt: new Date() }).where(eq(knowledgeDocuments.id, document.id)); return chunks.length }
knowledgeRoutes.get('/documents', async (c) => { const status = c.req.query('status'); const type = c.req.query('type'); const rows = await db.select().from(knowledgeDocuments).where(and(...(status ? [eq(knowledgeDocuments.status, status)] : []), ...(type ? [eq(knowledgeDocuments.type, type)] : []))).orderBy(desc(knowledgeDocuments.updatedAt)); return c.json(rows) })
knowledgeRoutes.post('/documents', async (c) => { const input = await body(c, createDocumentSchema); const [document] = await db.insert(knowledgeDocuments).values({ ...input, contentText: normalizeText(input.contentText), wordCount: wordCount(input.contentText), hash: contentHash(input.contentText), status: 'processing' }).returning(); const chunks = await indexDocument(document!); return c.json({ ...document, status: 'indexed', chunks }, 201) })
knowledgeRoutes.post('/documents/upload', async (c) => { const form = await c.req.formData(); const file = form.get('file'); if (!(file instanceof File)) return c.json({ error: 'Envie um arquivo.' }, 400); const supported = ['text/plain', 'text/markdown', 'application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']; if (!supported.includes(file.type) && !/\.(txt|md|markdown|pdf|docx)$/i.test(file.name)) return c.json({ error: 'Formato não permitido. Use TXT, MD, PDF ou DOCX.' }, 400); if (file.size > 20 * 1024 * 1024) return c.json({ error: 'O arquivo excede 20 MB.' }, 400); const raw = await file.text(); if (!raw.trim()) return c.json({ error: 'Não foi possível extrair texto do arquivo.' }, 422); const title = String(form.get('title') || file.name.replace(/\.[^.]+$/, '')); const tags = String(form.get('tags') || '').split(',').map((tag) => tag.trim()).filter(Boolean); const [document] = await db.insert(knowledgeDocuments).values({ title, type: file.name.endsWith('.md') ? 'markdown' : 'text', originalFilename: file.name, contentText: normalizeText(raw), wordCount: wordCount(raw), hash: contentHash(raw), tags, thesisId: (form.get('thesisId') as string) || null, status: 'processing' }).returning(); const chunks = await indexDocument(document!); return c.json({ ...document, status: 'indexed', chunks }, 201) })
knowledgeRoutes.get('/documents/:id', async (c) => { const id = c.req.param('id'); const [document] = await db.select().from(knowledgeDocuments).where(eq(knowledgeDocuments.id, id)); if (!document) notFound('Documento'); const chunks = await db.select().from(knowledgeChunks).where(eq(knowledgeChunks.documentId, id)).orderBy(knowledgeChunks.chunkIndex); return c.json({ ...document, chunks }) })
knowledgeRoutes.delete('/documents/:id', async (c) => { const deleted = await db.delete(knowledgeDocuments).where(eq(knowledgeDocuments.id, c.req.param('id'))).returning({ id: knowledgeDocuments.id }); if (!deleted.length) notFound('Documento'); return c.body(null, 204) })
knowledgeRoutes.post('/documents/:id/reindex', async (c) => { const [document] = await db.select().from(knowledgeDocuments).where(eq(knowledgeDocuments.id, c.req.param('id'))); if (!document) notFound('Documento'); const chunks = await indexDocument(document); return c.json({ id: document.id, status: 'indexed', chunks }) })
knowledgeRoutes.get('/search', async (c) => { const query = c.req.query('q')?.trim(); if (!query) return c.json({ error: 'O parâmetro q é obrigatório.' }, 400); return c.json(await searchKnowledge(query, { thesisId: c.req.query('thesisId'), type: c.req.query('type'), tags: c.req.query('tags')?.split(',').filter(Boolean) })) })
