import { asc, desc, eq } from 'drizzle-orm'
import { Hono } from 'hono'
import { promptTemplates, promptVersions } from '@/db/editorial-schema'
import { db } from '../db'
import { notFound } from './helpers'

export const promptRoutes = new Hono()
promptRoutes.get('/', async (c) => c.json(await db.select().from(promptTemplates).orderBy(asc(promptTemplates.name))))
promptRoutes.get('/:id', async (c) => { const [template] = await db.select().from(promptTemplates).where(eq(promptTemplates.id, c.req.param('id'))); if (!template) notFound('Prompt'); return c.json({ ...template, versions: await db.select().from(promptVersions).where(eq(promptVersions.promptTemplateId, template.id)).orderBy(desc(promptVersions.version)) }) })
promptRoutes.post('/', async (c) => { const input = await c.req.json() as { name: string; type: string; template: string; variables?: string[]; outputSchema?: Record<string, unknown> }; const [created] = await db.insert(promptTemplates).values({ ...input, variables: input.variables ?? [] }).returning(); return c.json(created, 201) })
promptRoutes.put('/:id', async (c) => { const patch = await c.req.json() as { template?: string; variables?: string[]; outputSchema?: Record<string, unknown>; active?: boolean }; const [current] = await db.select().from(promptTemplates).where(eq(promptTemplates.id, c.req.param('id'))); if (!current) notFound('Prompt'); await db.insert(promptVersions).values({ promptTemplateId: current.id, version: current.version, template: current.template, variables: current.variables ?? [], outputSchema: current.outputSchema ?? undefined }); const [updated] = await db.update(promptTemplates).set({ ...patch, version: current.version + 1, updatedAt: new Date() }).where(eq(promptTemplates.id, current.id)).returning(); return c.json(updated) })
promptRoutes.post('/:id/rollback/:version', async (c) => { const version = Number(c.req.param('version')); const [snapshot] = await db.select().from(promptVersions).where(eq(promptVersions.promptTemplateId, c.req.param('id'))).orderBy(desc(promptVersions.version)); if (!snapshot || snapshot.version !== version) notFound('Versão do prompt'); const [updated] = await db.update(promptTemplates).set({ template: snapshot.template, variables: snapshot.variables, outputSchema: snapshot.outputSchema, version: version + 1, updatedAt: new Date() }).where(eq(promptTemplates.id, c.req.param('id'))).returning(); return c.json(updated) })
promptRoutes.post('/:id/preview', async (c) => { const variables = await c.req.json() as Record<string, string>; const [template] = await db.select().from(promptTemplates).where(eq(promptTemplates.id, c.req.param('id'))); if (!template) notFound('Prompt'); return c.json({ preview: template.template.replace(/\{\{([^}]+)\}\}/g, (_, key: string) => variables[key.trim()] ?? `{{${key}}}`) }) })
